apiVersion: v1
kind: Pod
metadata:
  name: debug-console
spec:
  hostNetwork: true
  containers:
  - name: debug-console
    image: openbce/debug-console
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /run/dbus
      name: dbus
      readOnly: true
  volumes:
  - name: dbus
    hostPath:
      path: /run/dbus/
      type: Directory