apiVersion: v1
kind: Pod
metadata:
  name: debug-console
spec:
  hostNetwork: true
  containers:
  - name: debug-console
    image: openbce-console
    command:
      - /bin/bash
      - -c
      - "exec tail -f /dev/null"